steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'us-central1-docker.pkg.dev/ltc-reboot25-team-39/application-repo/resumescreeningapp:$COMMIT_SHA', '.'
    ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-central1-docker.pkg.dev/ltc-reboot25-team-39/application-repo/resumescreeningapp:$COMMIT_SHA'
    ]

  # Step 3: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/resumescreening-app'
      - 'producer=us-central1-docker.pkg.dev/ltc-reboot25-team-39/application-repo/resumescreeningapp:$COMMIT_SHA'
      - '--namespace=cortexcrew'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=resume-api'

images:
  - 'us-central1-docker.pkg.dev/ltc-reboot25-team-39/application-repo/resumescreeningapp:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/ltc-reboot25-team-39/serviceAccounts/852443649489-compute@developer.gserviceaccount.com
# retriggerring the cloud build