steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'us-central1-docker.pkg.dev/hireassist-465713/application-repo/consumer-api:$COMMIT_SHA', '.'
    ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-central1-docker.pkg.dev/hireassist-465713/application-repo/consumer-api:$COMMIT_SHA'
    ]

  # Step 3: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/resume-consumer'
      - 'resume-consumer=us-central1-docker.pkg.dev/hireassist-465713/application-repo/consumer-api:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=resume-api'

images:
  - 'us-central1-docker.pkg.dev/hireassist-465713/application-repo/consumer-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: projects/hireassist-465713/serviceAccounts/154305106622-compute@developer.gserviceaccount.com