apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-consumer
  template:
    metadata:
      labels:
        app: resume-consumer
    spec:
      containers:
      - name: resume-consumer
        image: us-central1-docker.pkg.dev/hireassist-465713/application-repo/consumer-api:latest
        resources:
          requests:
            cpu: "100m"
            memory: "384Mi"
          limits:
            cpu: "300m"
            memory: "768Mi"
        env:
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: kafka-creds
              key: BOOTSTRAP_SERVERS
        - name: SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-creds
              key: SASL_USERNAME
        - name: SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-creds
              key: SASL_PASSWORD
        ports:
        - containerPort: 8080